--liquibase formatted sql
--changeset GalaxyUser999:create-table-holiday-23-01-2026
CREATE TABLE Holiday (
    id int primary key generated by default as identity,
    holiday_name VARCHAR(100),
    holiday_date DATE
);